k9s:
  shellPod:
    image: nicolaka/netshoot:latest   # or your own admin image
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi  # adds the `s` shell action in node vie
  liveViewAutoRefresh: false
  refreshRate: 2
  maxConnRetry: 5
  readOnly: false
  noExitOnCtrlC: false
  ui:
    enableMouse: true
    headless: false
    logoless: true
    crumbsless: false
    noIcons: false
    skin: catppuccin-mocha-transparent
  skipLatestRevCheck: false
  disablePodCounting: false
  imageScans:
    enable: false
    exclusions:
      namespaces: []
      labels: {}
  logger:
    tail: 1000
    buffer: 5000
    sinceSeconds: -1
    textWrap: false
    showTime: false
